export type WorkspaceId = string
export type ProjectId = string
export type TemplateId = string
export type ScaffoldId = string
export type GeneratorId = string
export type CodegenId = string
export type BlueprintId = string
export type PresetId = string
export type ProfileId = string
export type CommandId = string
export type ArgumentId = string
export type OptionId = string
export type PluginId = string
export type ExtensionId = string
export type ManifestId = string
export type VersionString = string
export type Timestamp = string
export type LifecycleState = "draft" | "active" | "deprecated" | "archived"
export type CompatibilityState = "compatible" | "incompatible" | "partial"
