packages:
  - '.'
  - 'packages/*'
  - 'apps/*'
  - 'glowify-ai'

allowBuilds:
  '@firebase/util': set this to true or false
  '@google/genai': set this to true or false
  msgpackr-extract: set this to true or false
  protobufjs: set this to true or false
