export type AuthenticationId = string
export type IdentityId = string
export type UserId = string
export type AccountId = string
export type ProfileId = string
export type SessionId = string
export type DeviceId = string
export type CredentialId = string
export type TokenId = string
export type VerificationId = string
export type TenantId = string
export type OrganizationId = string
export type MembershipId = string
export type InvitationId = string
export type SecurityEventId = string
export type TrustScore = number
export type Timestamp = string
export type VersionString = string
export type ProviderName = string
export type AuthenticationLifecycleState = "draft" | "pending" | "active" | "suspended" | "locked" | "revoked" | "expired"
export type VerificationState = "pending" | "verified" | "failed" | "expired" | "revoked"
export type MultiFactorType = "totp" | "sms" | "email" | "push" | "backup_code" | "webauthn"
export type TokenType = "access" | "refresh" | "id" | "api_key"
