export type MessageId = string
export type TopicName = string
export type QueueName = string
export type ExchangeName = string
export type ChannelName = string
export type PartitionId = string
export type OffsetValue = number
export type ConsumerId = string
export type ProducerId = string
export type PublisherId = string
export type SubscriberId = string
export type SubscriptionId = string
export type BrokerId = string
export type StreamId = string
export type ConsumerGroupId = string
export type Timestamp = string
export type VersionString = string
export type PriorityLevel = "low" | "normal" | "high" | "critical"
export type DeliveryState = "pending" | "delivered" | "acked" | "nacked" | "failed" | "dead_lettered"
export type OrderingStrategy = "none" | "fifo" | "partition" | "priority"
