export type IntegrationId = string
export type IntegrationSessionId = string
export type IntegrationProviderId = string
export type ConnectorId = string
export type ConnectorInstanceId = string
export type ConnectionId = string
export type CredentialReferenceId = string
export type SecretReferenceId = string
export type InstallationId = string
export type SynchronizationId = string
export type SynchronizationJobId = string
export type WebhookId = string
export type WebhookEventId = string
export type WebhookSubscriptionId = string
export type Timestamp = string
export type VersionString = string
export type IntegrationState = "draft" | "installed" | "active" | "paused" | "suspended" | "failed" | "retired"
export type ExecutionState = "pending" | "running" | "succeeded" | "failed" | "cancelled" | "timed_out"
