export type ProviderId = string
export type ModelId = string
export type ModelVersionId = string
export type ConversationId = string
export type MessageId = string
export type PromptId = string
export type PromptVersionId = string
export type ToolId = string
export type ToolCallId = string
export type FunctionCallId = string
export type AgentId = string
export type AgentSessionId = string
export type TokenCount = number
export type CostAmount = number
export type Timestamp = string
export type VersionString = string
export type RoutingStrategy = "direct" | "fallback" | "balanced" | "latency" | "cost"
export type StreamState = "idle" | "starting" | "streaming" | "completed" | "cancelled" | "failed"
export type SafetyState = "unknown" | "safe" | "review" | "blocked" | "escalated"
